name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  lints: ^3.0.0
  test: ^1.24.0
